import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { createClient } from "@/utils/supabase/server";
import { logout } from "@/app/action/auth";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: {children: React.ReactNode }){
  const supabase = await createClient()
  const { data: {user} } = await supabase.auth.getUser()

  return (
    <html lang="en" className={'${geistSans .variable}${geistMono.variable} h-full antialised'}>
      <body className="min-h-full flex flex-col">
        <nav className="border-b px-6 py-3 flex gap-6">
          <Link href="/" className="font-semibold hover:underline">Home</Link>
          <Link href="/posts" className="hover:underline">Posts</Link>
          {/* user が存在すればログイン済み、なければ未ログイン */}
          {user ? (
            // ログイン済み：ログアウトボタンを表示
            // form の action に Server Action を渡すとボタン押下で実行される
            <form action={logout}>
              <button type="submit">ログアウト</button>
            </form>
          ):(
            // 未ログイン：ログイン・サインアップリンクを表示
            // <> </> はフラグメント。余分なdivを作らずに複数要素を並べられる
            <>
              <Link href="/login" className="hover:underline">ログイン</Link>
              <Link href="/register" className="hover:underline">サインアップ</Link>
            </>
          )}
        </nav>
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  )

}
